Rebranding bashutils as ebash.

diff --git a/bin/bashlint b/bin/bashlint
--- a/bin/bashlint
+++ b/bin/bashlint
@@ -6,9 +6,9 @@
 # as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
 # version.
 
-: ${BASHUTILS_HOME:=$(dirname $0)/..}
-: ${BASHUTILS:=${BASHUTILS_HOME}/share}
-source ${BASHUTILS}/bashutils.sh || { echo "Unable to source ${BASHUTILS}/bashutils.sh" ; exit 1 ; }
+: ${EBASH_HOME:=$(dirname $0)/..}
+: ${EBASH:=${EBASH_HOME}/share}
+source ${EBASH}/ebash.sh || { echo "Unable to source ${EBASH}/ebash.sh" ; exit 1 ; }
 
 # Options:
 # -q Quiet mode
@@ -62,9 +62,9 @@ for fname in $(grep -lr '^#!/.*bash' ${PATHS[@]} | grep -v '.hg'); do
     # Initial error state
     RC=0
 
-    # Ensure none of the scripts are using non-versioned /usr/local/share/bashutils
-    echo "${CONTENTS}" | egrep "(:|)/usr/local/share/bashutils(:|/|\"|$)" \
-        && fail "Non-versioned bashutils"
+    # Ensure none of the scripts are using non-versioned /usr/local/share/ebash
+    echo "${CONTENTS}" | egrep "(:|)/usr/local/share/ebash(:|/|\"|$)" \
+        && fail "Non-versioned ebash"
 
     # Ensure not using removed $(esource ...)
     echo "${CONTENTS}" | egrep '\s*\$\(esource ' \
@@ -74,7 +74,7 @@ for fname in $(grep -lr '^#!/.*bash' ${PATHS[@]} | grep -v '.hg'); do
     echo "${CONTENTS}" | egrep '(declare_globals|declare_exports|declare_args|declare_opts)' \
         && fail "Using removed declare_globals|declare_exports functions"
 
-    # Don't allow using removed legacy IFS bashutils functions
+    # Don't allow using removed legacy IFS ebash functions
     echo "${CONTENTS}" | egrep '(ifs_save|ifs_restore|ifs_nl|ifs_space|ifs_set)' \
         && fail "Using non-existent deprecated ifs_* functions"
 
