Use consistent line length of 120 instead of 80. Reformat code accordingly.

diff --git a/bin/bashlint b/bin/bashlint
--- a/bin/bashlint
+++ b/bin/bashlint
@@ -79,9 +79,8 @@ for fname in $(grep -lr '^#!/.*bash' ${PATHS[@]} | grep -v '.hg'); do
     echo "${CONTENTS}" | egrep '(ifs_save|ifs_restore|ifs_nl|ifs_space|ifs_set)' \
         && fail "Using non-existent deprecated ifs_* functions"
 
-    # Ensure we don't have any sloppy 'return' statements which don't specify what
-    # return code to use. Because this usually returns the prior return code which
-    # is generally not what is intended and causes 'set -e' problems.
+    # Ensure we don't have any sloppy 'return' statements which don't specify what return code to use. Because this
+    # usually returns the prior return code which is generally not what is intended and causes 'set -e' problems.
     echo "${CONTENTS}" | egrep '^[^#]*return(\s*;|$)' \
         && fail "Ambiguous return statements"
 
