Fix shebang in ebash with arguments. Disable fatal error handling as well. (#14)

diff --git a/bin/ebash b/bin/ebash
--- a/bin/ebash
+++ b/bin/ebash
@@ -127,23 +127,28 @@ else
             trap_add "rm -f ${SCRIPT}"
             cp "${SOURCE}" "${SCRIPT}"
 
-            # Disable fatal error handling as that will be handled by the actual script we invoke which
-            # will run in ebash environment. It's not our responsibility at this point.
-            nodie_on_abort
-            nodie_on_error
+            (
+                # Disable fatal error handling as that will be handled by the actual script we invoke which
+                # will run in ebash environment. It's not our responsibility at this point.
+                nodie_on_abort
+                nodie_on_error
 
-            # Replace shebang with EBASH environment.
-			read -r -d '' EBASH_PREAMBLE <<-EOF
-			#!/usr/bin/env bash
-			export EBASH_HOME="${EBASH_HOME}"
-			export EBASH="${EBASH}"
-			source "${EBASH}/ebash.sh" || { echo "Unable to source ${EBASH}/ebash.sh" ; exit 1 ; }
-			EOF
-			sed -i -e "s%^#!.*%${EBASH_PREAMBLE//$'\n'/\\n}%" "${SCRIPT}"
+                # Replace shebang with EBASH environment.
+				read -r -d '' EBASH_PREAMBLE <<-EOF
+				#!/usr/bin/env bash
+				export EBASH_HOME="${EBASH_HOME}"
+				export EBASH="${EBASH}"
+				export __EBASH_SAVE_DOC=${__EBASH_SAVE_DOC}
+				source "${EBASH}/ebash.sh" || { echo "Unable to source ${EBASH}/ebash.sh" ; exit 1 ; }
+				EOF
+                sed -i -e "s%^#!.*%${EBASH_PREAMBLE//$'\n'/\\n}%" "${SCRIPT}"
 
-            # Execute the new script with any arguments passed along
-            chmod +x "${SCRIPT}"
-            exec "${SCRIPT}" ${@:-}
+                # Execute the new script with any arguments passed along
+                chmod +x "${SCRIPT}"
+                exec "${SCRIPT}" ${@:-}
+            )
+
+            exit 0
         fi
 
         # Run the command, but pretend to be inside a try so that die doesn't print an ugly stack trace.
