Rebranding bashutils as ebash.

diff --git a/bin/ebench b/bin/ebench
--- a/bin/ebench
+++ b/bin/ebench
@@ -6,9 +6,9 @@
 # as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
 # version.
 
-: ${BASHUTILS_HOME:=$(dirname $0)/..}
-: ${BASHUTILS:=${BASHUTILS_HOME}/share}
-source "${BASHUTILS}/bashutils.sh" || { echo "Unable to source ${BASHUTILS}/bashutils.sh" ; exit 1 ; }
+: ${EBASH_HOME:=$(dirname $0)/..}
+: ${EBASH:=${EBASH_HOME}/share}
+source "${EBASH}/ebash.sh" || { echo "Unable to source ${EBASH}/ebash.sh" ; exit 1 ; }
 
 #-------------------------------------------------------------------------------
 # ebench
@@ -17,7 +17,7 @@ source "${BASHUTILS}/bashutils.sh" || { echo "Unable to source ${BASHUTILS}/bash
 #   operations in bash and helping you to understand the time spent on each.
 #
 #   This should at least help us determine what sort of performance effects we
-#   have as we change things in bashutils.  Or at least, it would do that once
+#   have as we change things in ebash.  Or at least, it would do that once
 #   we actually test useful things in here.  For now, it's mostly useful when
 #   you're willing to edit the script and add the timing of things you're
 #   curious about.
@@ -129,11 +129,11 @@ BENCH_simple_opt_parse()
 
 PREBENCH_debug_trap()
 {
-    BASHUTILS_LEVEL=0
-    #trap "[[ ${BASH_SUBSHELL} != ${BASHUTILS_LEVEL} ]] && { BASHUTILS_LEVEL=${BASH_SUBSHELL} ; edebug spawned new \$BASHPID ; }" DEBUG
-    #trap "[[ ${BASH_SUBSHELL} != ${BASHUTILS_LEVEL} ]] && { BASHUTILS_LEVEL=${BASH_SUBSHELL} ; :  ; }" DEBUG
-    trap "if [[ ${BASH_SUBSHELL} != ${BASHUTILS_LEVEL:-} ]] ; then
-            BASHUTILS_LEVEL=${BASH_SUBSHELL}
+    EBASH_LEVEL=0
+    #trap "[[ ${BASH_SUBSHELL} != ${EBASH_LEVEL} ]] && { EBASH_LEVEL=${BASH_SUBSHELL} ; edebug spawned new \$BASHPID ; }" DEBUG
+    #trap "[[ ${BASH_SUBSHELL} != ${EBASH_LEVEL} ]] && { EBASH_LEVEL=${BASH_SUBSHELL} ; :  ; }" DEBUG
+    trap "if [[ ${BASH_SUBSHELL} != ${EBASH_LEVEL:-} ]] ; then
+            EBASH_LEVEL=${BASH_SUBSHELL}
           fi " DEBUG
 }
 
@@ -162,8 +162,8 @@ BENCH_no_debug_trap()
 
 BENCH_no_debug_trap_plus_comparison()
 {
-    if [[ ${BASH_SUBSHELL} != ${BASHUTILS_LEVEL:-} ]] ; then
-        BASHUTILS_LEVEL=${BASH_SUBSHELL}
+    if [[ ${BASH_SUBSHELL} != ${EBASH_LEVEL:-} ]] ; then
+        EBASH_LEVEL=${BASH_SUBSHELL}
     fi
     debug_trap_shared
 }
diff --git a/bin/etest b/bin/etest
--- a/bin/etest
+++ b/bin/etest
@@ -8,20 +8,20 @@
 
 : ${EMSG_PREFIX:=time}
 
-: ${BASHUTILS_HOME:=$(dirname $0)/..}
-: ${BASHUTILS:=${BASHUTILS_HOME}/share}
-source ${BASHUTILS}/bashutils.sh || { echo "Unable to source bashutils." ; exit 1 ; }
-export BASHUTILS
+: ${EBASH_HOME:=$(dirname $0)/..}
+: ${EBASH:=${EBASH_HOME}/share}
+source ${EBASH}/ebash.sh || { echo "Unable to source ebash." ; exit 1 ; }
+export EBASH
 
-if [[ ${__BU_OS} == "Linux" ]] ; then
+if [[ ${__EBASH_OS} == "Linux" ]] ; then
     reexec --sudo
 fi
 
-# Normalize BASHUTILS path in case any tests depend on it looking... normal.
-# Note: wait until after sourcing so that we can let bashutils make sure we get
+# Normalize EBASH path in case any tests depend on it looking... normal.
+# Note: wait until after sourcing so that we can let ebash make sure we get
 # GNU readlink rater than BSD readlink.
-BASHUTILS_HOME=$(readlink -f "${BASHUTILS_HOME}")
-BASHUTILS=$(readlink -f "${BASHUTILS}")
+EBASH_HOME=$(readlink -f "${EBASH_HOME}")
+EBASH=$(readlink -f "${EBASH}")
 
 #-------------------------------------------------------------------------------------------------------------------------
 # GLOBAL SETUP
@@ -73,8 +73,8 @@ if [[ ${mount_ns} -eq 1 ]] && os linux && ! grep -qw docker /proc/$$/cgroup ; th
 fi
 
 declare -A _BU_CONF
-if [[ -r .bashutils ]] ; then
-    conf_read _BU_CONF .bashutils
+if [[ -r .ebash ]] ; then
+    conf_read _BU_CONF .ebash
 fi
 
 START_TIME=$SECONDS
@@ -187,7 +187,7 @@ assert_no_process_leaks()
 {
     # Error stacks generated here should produce output, even though etest has
     # them wrapped in a try.
-    __BU_INSIDE_TRY=0
+    __EBASH_INSIDE_TRY=0
 
     edebug "Waiting..."
     
@@ -315,7 +315,7 @@ run_single_test()
         # cgroup.  This subshell solves both issues.
         try
         {
-            export BASHUTILS BASHUTILS_HOME TEST_DIR_OUTPUT=${work_dir}
+            export EBASH EBASH_HOME TEST_DIR_OUTPUT=${work_dir}
             if [[ -n ${source} ]] ; then
                 source "${source}"
             fi
@@ -323,7 +323,7 @@ run_single_test()
             # Pretend that the test _not_ executing inside a try/catch so that the
             # error stack will get printed if part of the test fails, as if etest
             # weren't running it inside a try/catch
-            __BU_INSIDE_TRY=0
+            __EBASH_INSIDE_TRY=0
 
             # Create our temporary workspace in the directory specified by the caller
             efreshdir "${work_dir}"
diff --git a/bin/ibu b/bin/ibu
--- a/bin/ibu
+++ b/bin/ibu
@@ -7,20 +7,20 @@
 # version.
 
 # Allow calling function documentation in ibu.  This must happen before
-# sourcing bashutils.
-__BU_SAVE_DOC=1
+# sourcing ebash.
+__EBASH_SAVE_DOC=1
 
 reload()
 {
-    : ${BASHUTILS_HOME:=$(dirname $0)/..}
-    : ${BASHUTILS:=${BASHUTILS_HOME}/share}
-    source ${BASHUTILS}/bashutils.sh || { echo "Failed to source ${BASHUTILS}/bashutils.sh" ; exit 1 ; }
-    BASHUTILS=$(readlink -f ${BASHUTILS})
-    BASHUTILS_HOME=$(readlink -f ${BASHUTILS_HOME})
+    : ${EBASH_HOME:=$(dirname $0)/..}
+    : ${EBASH:=${EBASH_HOME}/share}
+    source ${EBASH}/ebash.sh || { echo "Failed to source ${EBASH}/ebash.sh" ; exit 1 ; }
+    EBASH=$(readlink -f ${EBASH})
+    EBASH_HOME=$(readlink -f ${EBASH_HOME})
 }
 reload
 
-HISTFILE=$(mktemp --tmpdir ibashutils_$$_XXXXXX)
+HISTFILE=$(mktemp --tmpdir iebash_$$_XXXXXX)
 trap_add "rm --force \"${HISTFILE}\""
 
 : ${IBU_PROMPT:=$(ecolor green)$'IBU>\n'$(ecolor none)}
@@ -45,7 +45,7 @@ protected_read()
 repl()
 {
     while true ; do
-        # Note: In typical bashutils style, I would probably use tryrc here,
+        # Note: In typical ebash style, I would probably use tryrc here,
         # but I want to make sure that all commands are executed in the same
         # shell.
         protected_read -e -r -p "${IBU_PROMPT}" cmd && rc=0 || rc=$?
@@ -86,7 +86,7 @@ if [[ -n "${load}" ]] ; then
     source "${load}"
 fi
 
-einfo "Bashutils $(lval BASHUTILS)"
+einfo "ebash $(lval EBASH)"
 
 repl
 
