Change etest to always capture output in etest.log.

diff --git a/etest b/etest
--- a/etest
+++ b/etest
@@ -10,7 +10,11 @@ fi
 source ${BASHUTILS}/bashutils.sh || { echo "Unable to source bashutils." ; exit 1 ; }
 export BASHUTILS
 
-# Parse arguments. If no test directory was provided use PWD.
+#-------------------------------------------------------------------------------------------------------------------------
+# GLOBAL SETUP
+#-------------------------------------------------------------------------------------------------------------------------
+
+# If no test directory was provided use PWD.
 $(declare_args -g ?TEST_DIR)
 : ${TEST_DIR:=$(readlink -f .)}
 ETEST_TOPDIR=${TEST_DIR}
@@ -35,6 +39,22 @@ export ETEST_CGROUP_BASE="etest/$(basename ${TEST_DIR})"
 export ETEST_CGROUP="${ETEST_CGROUP_BASE}/$$"
 
 ETEST_BREAK_EXIT_CODE=25
+
+# Setup logfile
+exec {ETEST_STDERR_FD}<&2
+
+[[ -t 2 ]] && export EINTERACTIVE=1 || export EINTERACTIVE=0
+ETEST_LOG=${TEST_DIR}/etest.log
+elogfile -r=1 -t=${VERBOSE} ${ETEST_LOG}
+
+# Setup eTEST_OUTions for the "etest" outpu tand actual "test" output
+if [[ ${VERBOSE} -eq 0 ]]; then
+    ETEST_OUT="/proc/self/fd/${ETEST_STDERR_FD}"
+    TEST_OUT="/dev/null"
+else
+    ETEST_OUT="/dev/null"
+    TEST_OUT="/dev/stderr"
+fi
 
 #-------------------------------------------------------------------------------------------------------------------------
 # TEST UTILITY FUNCTIONS
@@ -101,93 +121,9 @@ global_teardown()
 {
     edebug "Starting global_teardown: PID=$$ BASHPID=${BASHPID} PPID=${PPID}"
 
-    argcheck TEST_DIR_OUTPUT
-    if [[ ${ETEST_CLEAN:-1} -ne 0 ]] ; then
-        eunmount_recursive ${TEST_DIR_OUTPUT} &>$(edebug_out)
-        rm -rf ${TEST_DIR_OUTPUT}
-    fi
-
-    edebug "Finished global_teardown"
-    return 0
-}
-
-call_file_setup()
-{
-    edebug "Starting call_file_setup"
-
-    # Unit test infrastructure setup
-    argcheck TEST_DIR_OUTPUT
-    efreshdir ${TEST_DIR_OUTPUT}/${testfilename}
-
-    # Unit test provided setup
-    if declare -f file_setup &>/dev/null ; then
-        einfos "FILE Setup"
-        file_setup &> ${REDIRECT}
-        eend
-    fi
-
-    edebug "Finished call_file_setup"
-    return 0
-}
-
-call_file_teardown()
-{
-    edebug "Starting call_file_teardown"
-
-    # Unit test provided teardown
-    if declare -f file_teardown &>/dev/null ; then
-        einfos "FILE Teardown"
-        $(tryrc file_teardown) &> ${REDIRECT}
-        eend
-    fi
-
-    # Unit test infrastructure teardown
-    if [[ ${ETEST_CLEAN:-1} -ne 0 ]] ; then
-        eunmount_recursive ${TEST_DIR_OUTPUT}/${testfilename} &>$(edebug_out)
-        rm -rf ${TEST_DIR_OUTPUT}/${testfilename}
-    fi
-
-    edebug "Finished call_file_teardown"
-    return 0
-}
-
-call_test_setup()
-{
-    # Unit test infrastructure setup
-    argcheck TEST_DIR_OUTPUT
-    mkdir -p ${TEST_DIR_OUTPUT}/${testfilename}/${testfunc}
-
-    # Unit test provided setup
-    if declare -f setup &>/dev/null ; then
-        etestmsg "Calling test_setup"
-        setup &> ${REDIRECT}
-        eend
-    fi
-
-    cd ${TEST_DIR_OUTPUT}/${testfilename}/${testfunc}
+    eunmount_recursive ${TEST_DIR_OUTPUT} &>$(edebug_out)
     
-    return 0
-}
-
-call_test_teardown()
-{
-    # Unit test provided teardown
-    if declare -f teardown &>/dev/null ; then
-        etestmsg "Calling test_teardown"
-        $(tryrc teardown) &> ${REDIRECT}
-        eend
-    fi
-
-    assert_no_process_leaks
-
-    # Unit test infrastructure teardown
-    argcheck testfunc
-    if [[ ${ETEST_CLEAN:-1} -ne 0 ]] ; then
-        eunmount_recursive ${TEST_DIR_OUTPUT}/${testfunc} &>$(edebug_out)
-        rm -rf ${TEST_DIR_OUTPUT}/${testfunc}
-    fi
-
-    edebug "Finished test_teardown"
+    edebug "Finished global_teardown"
     return 0
 }
 
@@ -196,55 +132,53 @@ run_single_test()
     local testfile=$1
     local testfunc=$2
     local testfilename=$(basename ${testfile})
+    local rc=0
 
-    # If debugging is not enabled for testfunc just show a brief message with test name
-    testfunc_rc=0
-    
-    if [[ ${VERBOSE} -eq 1 ]]; then
-        ebanner "${testfunc}" REPEAT=REPEAT_STRING
-    else
-        einfos ${testfunc}
-    fi
+    source ${testfile}
+    declare -f ${testfunc} &>/dev/null || return 0
 
+    ebanner "${testfunc}" REPEAT=REPEAT_STRING
+ 
+    einfos ${testfunc} &>${ETEST_OUT}
+   
+    # We want to make sure that any traps from the tests
+    # execute _before_ we run teardown, and also we don't
+    # want the teardown to run inside the test-specific
+    # cgroup.  This subshell solves both issues.
+    try
     {
-        try
-        {
-            # We want to make sure that any traps from the tests
-            # execute _before_ we run teardown, and also we don't
-            # want the teardown to run inside the test-specific
-            # cgroup.  This subshell solves both issues.
-            (
-                cgroup_create ${ETEST_CGROUP}
-                cgroup_move ${ETEST_CGROUP} $BASHPID
+        cgroup_create ${ETEST_CGROUP}
+        cgroup_move ${ETEST_CGROUP} ${BASHPID}
 
-                call_test_setup
+        # Unit test provided setup
+        if declare -f setup &>/dev/null ; then
+            etestmsg "Calling test_setup"
+            setup
+        fi
+        
+        cd ${TEST_DIR_OUTPUT}/${testfilename}/${testfunc}
 
-                etestmsg "Calling test"
-                ${testfunc}
-            )
+        etestmsg "Calling test"
+        ${testfunc}
+    }
+    catch
+    {
+        rc=$?
+    }
 
-            call_test_teardown
-        }
-        catch
-        {
-            testfunc_rc=$?
-            eend ${testfunc_rc}
-            $(tryrc call_test_teardown)
-            [[ ${rc} -eq 0 ]] || ewarn "${testfunc} teardown failed."
-            FAILED_TESTS+=( ${testfunc/ETEST_/} )
-
-            [[ ${BREAK} -eq 0 ]] || die -r=${ETEST_BREAK_EXIT_CODE} "${testfunc} failed and BREAK=1"
-        }
-
-    } &> ${REDIRECT}
-
-    if [[ ${VERBOSE} -eq 0 ]] ; then
-        eend ${testfunc_rc}
+    if [[ ${rc} -eq 0 ]]; then
+        einfo "$(ecolor green)${testfunc} PASSED."
     else
-        [[ ${testfunc_rc} -eq 0 ]] \
-            && einfo "$(ecolor green)${testfunc} PASSED." \
-            || eerror "${testfunc} FAILED."
+        eerror "${testfunc} FAILED."
     fi
+
+    # Unit test provided teardown
+    if declare -f teardown &>/dev/null ; then
+        etestmsg "Calling test_teardown"
+        $(tryrc teardown)
+    fi
+
+    return ${rc}
 }
 
 run_all_tests_in_file()
@@ -254,57 +188,59 @@ run_all_tests_in_file()
 
     FAILED_TESTS=()
 
-    # Skip files that don't contain any tests
-    grep -q "^ETEST_" ${testfile} >/dev/null || return 0
-
     # Skip files whose name matches the exclude filter
     [[ -n ${EXCLUDE} && ${testfile} =~ ${EXCLUDE} ]] && return 0
 
-    try
-    {
-        source ${testfile}
+    # Ensure proper shebang is in the unit test or else bashlint won't be able to validate it
+    # and it may not be a proper bash unit test
+    grep -q '^#!/.*bash' ${testfile} || { eerror "No bash shebang in ${testfile}"; throw 1; }
 
-        # Ensure proper shebang is in the unit test or else bashlint won't be able to validate it
-        # and it may not be a proper bash unit test
-        grep -q '^#!/.*bash' ${testfile} || { eerror "No bash shebang in ${testfile}"; throw 1; }
+    # Get all function names that begin with ETEST_ (and optionally match $2)
+    if [[ ${testfile} =~ ${FILTER} ]]; then
+        ETEST_FUNCTIONS=( $(source ${testfile}; declare -F | awk '$3 ~ "^ETEST" {print $3}' ) )
+    else
+        ETEST_FUNCTIONS=( $(source ${testfile}; declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'${FILTER}'" {print $3}') )
+    fi
+    edebug $(lval testfile ETEST_FUNCTIONS)
 
-        # Get all function names that begin with ETEST_ (and optionally match $2)
-        [[ ${testfile} =~ ${FILTER} ]] && ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" {print $3}' ) ) \
-                                       || ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'${FILTER}'" {print $3}') )
+    [[ ${#ETEST_FUNCTIONS[@]} -gt 0 ]] || return 0
 
-        [[ ${#ETEST_FUNCTIONS[@]} -gt 0 ]] || continue
-
-        # Exclude those functions that match the exclude filter
-        if [[ -n ${EXCLUDE} ]] ; then
-            for index in "${!ETEST_FUNCTIONS[@]}" ; do
-                if [[ ${ETEST_FUNCTIONS[$index]} =~ ${EXCLUDE} ]] ; then
-                    unset ETEST_FUNCTIONS[$index]
-                fi
-            done
-        fi
-
-        [[ ${VERBOSE} -eq 1 ]] || einfo "Starting tests in ${testfile} ${REPEAT_STRING}"
-
-        call_file_setup
-
-        for testfunc in ${ETEST_FUNCTIONS[@]}; do
-            run_single_test ${testfile} ${testfunc}
+    # Exclude those functions that match the exclude filter
+    if [[ -n ${EXCLUDE} ]] ; then
+        for index in "${!ETEST_FUNCTIONS[@]}" ; do
+            if [[ ${ETEST_FUNCTIONS[$index]} =~ ${EXCLUDE} ]] ; then
+                unset ETEST_FUNCTIONS[$index]
+            fi
         done
+    fi
 
-        call_file_teardown
-    }
-    catch
-    {
-        if [[ $? -eq ${ETEST_BREAK_EXIT_CODE} ]] ; then
-            exit ${ETEST_BREAK_EXIT_CODE}
-        fi
+    einfo "Starting tests in ${testfile} ${REPEAT_STRING}" &>${ETEST_OUT}
 
-        FAILED_FILES+=( ${testfilename} ) || true
-    }
+    for testfunc in file_setup ${ETEST_FUNCTIONS[@]} file_teardown; do
+     
+        # Unit test infrastructure setup
+        efreshdir ${TEST_DIR_OUTPUT}/${testfilename}/${testfunc}
+       
+        try
+        {
+            run_single_test ${testfile} ${testfunc} |& tee -a ${ETEST_LOG} &>${TEST_OUT}
+            eend &>${ETEST_OUT}
+        }
+        catch
+        {
+            eend $? &>${ETEST_OUT}
+            [[ ${BREAK} -eq 0 ]] || die "${testfunc} failed and BREAK=1" &>${ETEST_OUT}
+            FAILED_FILES+=( ${testfilename} )
+        }
+
+        # Unit test infrastructure teardown
+        assert_no_process_leaks
+        eunmount_recursive ${TEST_DIR_OUTPUT}/${testfilename}/${testfunc} &>$(edebug_out)
+    done
 }
 
 #-------------------------------------------------------------------------------------------------------------------------
-# MAIN
+# GLOBAL SETUP
 #-------------------------------------------------------------------------------------------------------------------------
 
 FAILED_FILES=()
@@ -351,8 +287,6 @@ fi
 #-------------------------------------------------------------------------------------------------------------------------
 # MAIN
 #-------------------------------------------------------------------------------------------------------------------------
-
-[[ ${VERBOSE} -eq 1 ]] && REDIRECT="/dev/stderr" || REDIRECT="/dev/null"
 
 # Now go through and test all unit tests
 for (( ITERATION=1; ITERATION<=${REPEAT}; ITERATION++ )); do
