Run every etest unittest in its own directory and clean it automatically on success

diff --git a/etest b/etest
--- a/etest
+++ b/etest
@@ -8,9 +8,9 @@ source $(dirname $0)/efuncs.sh || source ${BASHUTILS}/efuncs.sh || { echo "Unabl
 TEST_DIR=$1
 esource ${TEST_DIR}/*.sh
 
-#-----------------------------------------------------------------------------
+#-------------------------------------------------------------------------------------------------------------------------
 # TEST UTILITY FUNCTIONS
-#-----------------------------------------------------------------------------
+#-------------------------------------------------------------------------------------------------------------------------
 
 expect_true()
 {
@@ -38,16 +38,14 @@ expect_op()
 
 expect_eq()
 {
-    local lh="$1"
-    local rh="$2"
-    expect_op "\"${lh}\"" "==" "\"${rh}\""
+    eval $(declare_args ?lh ?rh)
+    [[ "${lh}" == "${rh}" ]] || { eerror "expect_eq failed :: $(lval lh rh)"; return 1; } 
 }
 
 expect_ne()
 {
-    local lh="$1"
-    local rh="$2"
-    expect_op "\"${lh}\"" "!=" "\"${rh}\""
+    eval $(declare_args ?lh ?rh)
+    [[ ! "${lh}" == "${rh}" ]] || { error "expect_ne failed :: $(lval lh rh)"; return 1; }
 }
 
 expect_zero()
@@ -70,13 +68,12 @@ expect_not_empty()
     [[ $1 != "" ]] || { eerror "expect_not_empty received an empty string." ; return 1 ; }
 }
 
-#-----------------------------------------------------------------------------
+#-------------------------------------------------------------------------------------------------------------------------
 # MAIN
-#-----------------------------------------------------------------------------
+#-------------------------------------------------------------------------------------------------------------------------
 
 # Get all function names that begin with ETEST_ (and optionally match $2)
 ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'$2'" {print $3}') )
-
 
 # Figure out longest test name
 ETEST_LONGEST=0
@@ -94,8 +91,21 @@ for testfunc in "${ETEST_FUNCTIONS[@]}" ; do
     msg=$(printf "%s%${pad}s" "${testfunc}" " ")
 
     [[ -n ${EDEBUG} ]] && einfo "${msg}" || einfon "${msg}"
-    ( ${testfunc} )
+
+    # Create a specific directory to run this test in. That way the test can create whatever directories and files it
+    # needs and assuming the test succeeds we'll auto remove the directory after the test completes.
+    TEST_DIR_OUTPUT="${TEST_DIR}/output/${testfunc}"
+    (
+        emkdir ${TEST_DIR_OUTPUT}
+        cd ${TEST_DIR_OUTPUT}
+        edebug "Running ${testfunc} in $(pwd)"
+        ${testfunc}
+    )
     rc=$?
+
+    # If the test succeeded remove it's contents
+    [[ ${ETEST_CLEAN:-1} -eq 1 && ${rc} -eq 0 ]] && { edebug "Cleaning ${TEST_DIR_OUTPUT}"; erm ${TEST_DIR_OUTPUT}; }
+
     (( ETEST_RC += $rc ))
     eend $rc
 
