Review K257078 - put path back correctly in etest

diff --git a/etest b/etest
--- a/etest
+++ b/etest
@@ -7,8 +7,7 @@ if [[ $(id -u) != "0" ]]; then
 fi
 
 : ${BASHUTILS:=$(dirname $0)}
-PATH=".:${PATH}:${BASHUTILS}"
-source efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
+source $(dirname $0)/efuncs.sh || source ${BASHUTILS}/efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
 
 [[ -z ${1} || -n ${3} ]] && die "etest only accepts one or two arguments"
 TEST_DIR=$(readlink -m $1)
