Use readlink -m instead of -f in emount utilities.  Disabled dangerous chroot test.  Make eend write to end of previous line.

diff --git a/etest b/etest
--- a/etest
+++ b/etest
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-: ${BASHUTILS:=/usr/local/share/bashutils}
+## Check if we're root and re-execute if we're not through sudo ##
+if [[ $(id -u) != "0" ]]; then
+    sudo -E "$0" "$@"
+    exit $?
+fi
+
+: ${BASHUTILS:=$(dirname $0)}
 PATH=".:${PATH}:${BASHUTILS}"
 source efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
 
 [[ -z ${1} || -n ${3} ]] && die "etest only accepts one or two arguments"
-
 TEST_DIR=$1
-$(esource ${TEST_DIR}/*.sh)
+FILTER=$2
 
 #-------------------------------------------------------------------------------------------------------------------------
 # TEST UTILITY FUNCTIONS
@@ -69,57 +74,108 @@ assert_not_empty()
     [[ $1 != "" ]] || { die "assert_not_empty received an empty string." ; return 1 ; }
 }
 
-#-------------------------------------------------------------------------------------------------------------------------
-# MAIN
-#-------------------------------------------------------------------------------------------------------------------------
-
-# Get all function names that begin with ETEST_ (and optionally match $2)
-ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'$2'" {print $3}') )
-
-# Figure out longest test name
-ETEST_LONGEST=0
-ETEST_LEN=0
-for testfunc in "${ETEST_FUNCTIONS[@]}"; do
-    ETEST_LEN=${#testfunc}
-    (( ETEST_LEN > ETEST_LONGEST )) && ETEST_LONGEST=${ETEST_LEN}
-done
-
-edebug "Running tests $(lval ETEST_FUNCTIONS)"
-# And execute them
-ETEST_RC=0
-for testfunc in "${ETEST_FUNCTIONS[@]}" ; do
-
-    # If debugging is not enabled for testfunc just show a brief message with test name
-    if edebug_enabled ${testfunc}; then
-        ebanner ${testfunc}
-    else
-        pad=$((ETEST_LONGEST-${#testfunc}+1))
-        msg=$(printf "%s%${pad}s" "${testfunc}" " ")
-        einfon "${msg}"
-    fi
-
+global_setup()
+{
     # Create a specific directory to run this test in. That way the test can create whatever directories and files it
     # needs and assuming the test succeeds we'll auto remove the directory after the test completes.
     TEST_DIR_OUTPUT="${TEST_DIR}/output/${testfunc}"
-    
-    eval "${testfunc}_internal() { 
-    (
-        emkdir ${TEST_DIR_OUTPUT}
-        cd ${TEST_DIR_OUTPUT}
-        ${testfunc}
-    ) &> \$(edebug_out)
-    }"
+    emkdir ${TEST_DIR_OUTPUT}
+    cd ${TEST_DIR_OUTPUT}
+}
 
-    ${testfunc}_internal
-    rc=$?
+global_teardown()
+{
+    argcheck TEST_DIR_OUTPUT
 
     # If the test succeeded remove it's contents
-    [[ ${ETEST_CLEAN:-1} -eq 1 && ${rc} -eq 0 ]] \
-        && { edebug "Cleaning ${TEST_DIR_OUTPUT}"; eunmount_recursive ${TEST_DIR_OUTPUT} &>$(edebug_out); erm ${TEST_DIR_OUTPUT}; }
+    if [[ ${ETEST_CLEAN:-1} -eq 1 && ${rc} -eq 0 ]] ; then
+        edebug "Cleaning ${TEST_DIR_OUTPUT}"
 
-    (( ETEST_RC += $rc ))
-    edebug_enabled ${testfunc} || eend ${rc}
+        [[ $(id -u) == 0 ]] && eunmount_recursive ${TEST_DIR_OUTPUT} &>$(edebug_out)
+        erm ${TEST_DIR_OUTPUT}
+    fi
+}
 
+run_setup()
+{
+    global_setup
+    declare -f setup &>/dev/null && { setup || die "Setup failed." ; }
+    return 0
+}
+
+run_teardown()
+{
+    declare -f teardown &>/dev/null && { teardown || die "Setup failed." ; }
+    global_teardown
+    return 0
+}
+
+#-------------------------------------------------------------------------------------------------------------------------
+# MAIN
+#-------------------------------------------------------------------------------------------------------------------------
+for testfile in ${TEST_DIR}/*.sh ; do
+    # Each test file gets its own subshell
+    (
+        ETEST_RC=0
+        $(esource ${testfile})
+
+        # Get all function names that begin with ETEST_ (and optionally match $2)
+        ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'${FILTER}'" {print $3}') )
+
+        # Figure out longest test name
+        ETEST_LONGEST=0
+        ETEST_LEN=0
+        for testfunc in "${ETEST_FUNCTIONS[@]}"; do
+            ETEST_LEN=${#testfunc}
+            (( ETEST_LEN > ETEST_LONGEST )) && ETEST_LONGEST=${ETEST_LEN}
+        done
+
+        if [[ ${#ETEST_FUNCTIONS[@]} -eq 0 ]] ; then
+            einfo "Skipping ${testfile}.  No tests found.\n"
+            continue
+        fi
+
+        einfo "Starting tests in ${testfile}"
+
+        edebug "Running tests $(lval ETEST_FUNCTIONS)"
+        # And execute them
+        ETEST_RC=0
+        for testfunc in "${ETEST_FUNCTIONS[@]}" ; do
+
+            # If debugging is not enabled for testfunc just show a brief message with test name
+            if edebug_enabled ${testfunc}; then
+                ebanner ${testfunc}
+            else
+                pad=$((ETEST_LONGEST-${#testfunc}+1))
+                msg=$(printf "%s%${pad}s" "${testfunc}" " ")
+                einfos "${msg}"
+            fi
+
+            eval "${testfunc}_internal() { 
+            (
+                run_setup
+                ${testfunc}
+                rc=\$?
+                run_teardown
+                exit \$rc
+            ) &> \$(edebug_out)
+            }"
+
+            ${testfunc}_internal
+            rc=$?
+
+            (( ETEST_RC += $rc ))
+            edebug_enabled ${testfunc} || eend ${rc}
+
+        done
+
+        if [[ ${ETEST_RC} -eq 0 ]] ; then
+            einfo "Tests passed: ${testfile}\n"
+        else
+            eerror "Tests failed: ${testfile}\n"
+        fi
+
+    )
 done
 
 exit ${ETEST_RC}
