Put unit test processes in cgroups and watch for stale remnants.

diff --git a/etest b/etest
--- a/etest
+++ b/etest
@@ -7,8 +7,9 @@ if [[ $(id -u) != "0" ]]; then
 fi
 
 : ${BASHUTILS:=$(dirname $0)}
-source $(dirname $0)/efuncs.sh || source ${BASHUTILS}/efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
+source ${BASHUTILS}/efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
 
+$(esource ${BASHUTILS}/cgroup.sh)
 [[ "$#" -eq 1 || "$#" -eq 2 ]] || die "etest only accepts one or two arguments"
 TEST_DIR=$(readlink -m $1)
 FILTER=${2:-}
@@ -23,10 +24,24 @@ global_setup()
     # needs and assuming the test succeeds we'll auto remove the directory after the test completes.
     TEST_DIR_OUTPUT="${TEST_DIR}/output"
     mkdir -p ${TEST_DIR_OUTPUT}
+
+    [[ -n "$(cgroup_pids etest)" ]] && { ewarn "Killing stale etest processes" ; cgroup_kill_and_wait -s=SIGKILL etest ; }
+
+    # And a cgroup that will contain all output
+    cgroup_create etest
+    cgroup_move etest $$
 }
 
 global_teardown()
 {
+    edebug "etest global teardown"
+
+    # Verify no remaining processes and shut things down
+    local remaining_processes=$(cgroup_ps etest)
+    [[ -n ${remaining_processes} ]] && { eerror "Stale processes:"  ; eerror "${remaining_processes}" ; }
+    cgroup_kill_and_wait -x="$$ ${BASHPID}" -s=SIGKILL etest
+    cgroup_destroy -r etest
+
     argcheck TEST_DIR_OUTPUT
     if [[ ${ETEST_CLEAN:-1} -ne 0 ]] ; then
         eunmount_recursive ${TEST_DIR_OUTPUT}
@@ -40,6 +55,10 @@ test_setup()
     argcheck TEST_DIR_OUTPUT
     mkdir -p ${TEST_DIR_OUTPUT}/${testfunc}
 
+    export ETEST_CGROUP=etest/${testfunc}
+    cgroup_create ${ETEST_CGROUP}
+    cgroup_move ${ETEST_CGROUP} ${BASHPID}
+
     # Unit test provided setup
     declare -f setup &>/dev/null && { setup || die "Setup failed." ; } 
 
@@ -48,8 +67,17 @@ test_setup()
 
 test_teardown()
 {
+    edebug "Tearing down for test ${testfunc}"
+
     # Unit test provided teardown
     declare -f teardown &>/dev/null && { teardown || die "Setup failed." ; }
+
+    # Verify no remaining processes and shut things down
+    ETEST_CGROUP=etest/${testfunc}
+    local remaining_processes=$(cgroup_ps ${ETEST_CGROUP})
+    [[ -n ${remaining_processes} ]] && { eerror "Stale processes:"  ; eerror "${remaining_processes}" ; }
+    cgroup_kill_and_wait -x="$$ ${BASHPID}" -s=SIGKILL ${ETEST_CGROUP}
+    cgroup_destroy -r ${ETEST_CGROUP}
 
     # Unit test infrastructure teardown
     argcheck testfunc
@@ -65,13 +93,11 @@ test_teardown()
 # SANITY TEST OF DIE FUNCTIONALITY
 #-------------------------------------------------------------------------------------------------------------------------
 
-global_setup
-
 # Manually test die() functionality outside of try/catch to ensure basic trap functionality works properly.
 DIE_TEST_MSG="Verifying die() trap functionality"
 edebug_enabled && ebanner "${DIE_TEST_MSG}" || einfo "${DIE_TEST_MSG}"
 {
-    DIE_FILE="${TEST_DIR_OUTPUT}/etest_die.txt"
+    DIE_FILE="etest_die.txt"
     rm -f ${DIE_FILE}
 
     die_handler()
@@ -147,14 +173,13 @@ for testfile in $(find ${TEST_DIR}/*.sh); do
                 test_setup
                 cd ${TEST_DIR_OUTPUT}/${testfunc}
                 ${testfunc}
-                test_teardown
             } &> $(edebug_out) 
             catch
             {
                 testfunc_rc=$?
                 FAILED_TESTS+=( ${testfunc/ETEST_/} )
-                test_teardown
             }
+            test_teardown
 
             eend ${testfunc_rc}
            
